### ISSUE TITLE
[Feature] Include index in List Transition

### ISSUE THREAD

**Issue by A1X5H04** [Daydreamer-riri/transition-hooks#4]
Guess I am here again 😅, I was creating a complex form with array, When using the list transition I find out that it does not include index which is necessary to differentiate between forms items, I request you to add include index in the list transition just like how the map does

```js
array.map(item, index) => (
<div>
<input name={`item.${index}.value}`}
                      ^= (index is necessary to differentiate)
</div>

))

```

**Comment by Daydreamer-riri** [comment]
ListTransition does not provide `index` because it has no semantics (the index used by its internal map is not the same as the index of the state array because it contains the element being retired).

You can use `key`:
```tsx
<>
  {transition((item, { key }) => (
    <input name={key} />
  )}
<>
```

If you don't pass `keyExtractor`, the key is a self-incrementing number with no semantics. You can use `keyExtractor` to make the `key` of each item semantic.

**Comment by Daydreamer-riri** [comment]
Hi @A1X5H04 , I'm going to close this issue. Do you have any questions?

**Comment by A1X5H04** [comment]
No, thanks for your reply
